services:
  api:
    image: ai-assistant-api
    working_dir: /app
    command: pnpm turbo dev --filter=@ai/api
    volumes:
      #      - .:/app
      - /app/node_modules
    build:
      context: .
      dockerfile: infra/docker/api.dev.Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - db

  web:
    image: ai-assistant-web
    working_dir: /app
    command: pnpm turbo dev --filter=@ai/web
    volumes:
      #      - .:/app
      - /app/node_modules
    build:
      context: .
      dockerfile: infra/docker/web.dev.Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - api

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pma
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
